/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_opengl_c_es_MyGLView */

#ifndef _Included_com_example_opengl_c_es_MyGLView
#define _Included_com_example_opengl_c_es_MyGLView
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_opengl_c_es_MyGLView
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_opengl_1c_1es_MyGLView_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_example_opengl_c_es_MyGLView
 * Method:    nativeResize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_opengl_1c_1es_MyGLView_nativeResize
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_example_opengl_c_es_MyGLView
 * Method:    nativeRender
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_opengl_1c_1es_MyGLView_nativeRender
  (JNIEnv *, jclass);

/*
 * Class:     com_example_opengl_c_es_MyGLView
 * Method:    nativeDone
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_opengl_1c_1es_MyGLView_nativePause
  (JNIEnv *, jclass);
JNIEXPORT void JNICALL Java_com_example_opengl_1c_1es_MyGLView_nativePushTexture
  (JNIEnv *, jclass,jintArray,jint,jint);

#ifdef __cplusplus
}
#endif
#endif
